project:
  type: website
  # output-dir: docs

website:
  # title: "Leon Cheng's wedsite"
  reader-mode: true
  navbar:
    title: false
    background: white
    foreground: "gray-800"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects        
      - about.qmd

  page-footer:
    right: "&copy; 2025, Ziteng Cheng"

format:
  html:
    theme:
      - cos
      - brand
    css: styles.css
    toc: true

editor: visual

