project:
  type: website
  # output-dir: docs

website:
  # title: "Leon Cheng's wedsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects        
      - about.qmd

format:
  html:
    theme:
      - cos
      - brand
    css: styles.css
    toc: true

editor: visual

